name: webviewx
description: A feature-rich cross-platform webview using webview_flutter for
  mobile and iframe for web. JS interop-ready.
homepage: https://github.com/adrianflutur/webviewx
version: 0.4.2

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  path: ^1.8.2
  pointer_interceptor: ^0.9.3+3
  uuid: ^4.5.1
  webview_flutter: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
